{{ if eq .Values.ingress.enabled true }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: {{ .Values.ossexporter.name }}
 namespace: {{ .Values.namespace }}
 labels:
    app: {{ .Values.ossexporter.name }}
 annotations:
   kubernetes.io/ingress.class: nginx
   nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
 #tls:
 # - hosts:
 #   - {{ .Values.ossexporter.host }}
 #   secretName: wildcard-tls
 rules:
 - host: {{ .Values.ossexporter.host }}
   http:
     paths:
     - path: /
       backend:
         serviceName: {{ .Values.ossexporter.name }}
         servicePort: {{ .Values.service.port }}

{{ end }}
