---
# Source: oss-exporter/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  namespace: vault
  name: oss-exporter
  labels:
    app.kubernetes.io/name: oss-exporter
    helm.sh/chart: oss-exporter-0.0.4
    app.kubernetes.io/instance: oss-exporter
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports: 
    - port: 9340
      targetPort: 9340
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: oss-exporter
    app.kubernetes.io/instance: oss-exporter
